# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: required
dist: trusty

# https://docs.travis-ci.com/user/installing-dependencies/#Installing-Packages-with-the-APT-Addon
addons:
  apt:
    packages:
      - google-chrome-stable

language: node_js

node_js:
  - "8"

before_script:
  - "yarn dist"

# https://blog.travis-ci.com/2013-12-05-speed-up-your-builds-cache-your-dependencies
cache:
  yarn: true
  directories:
    - "node_modules"

notifications:
  email: false

# https://docs.travis-ci.com/user/deployment/npm/
#deploy:
# api_key:
#    secure: IF6bjeaql6tqF9v0zt1uepnsVEzCHw1bx8iJaPbfsK26YlddY/bghH6ttkPbpASWA42C/+8oejBiTl5ETjmq4No6NhF7xMALBMx1/bz8sh4Gm/LXMTKDdtWffPAiBUZvkLYTJOIHfLfDhMMjHCahqW1wYUVN3kKL3zMairdatJa7ZGuube4R5+RYWCQU3Fe9TJdgKc3h0o/ObjJAX0h50V3j2jTqSJiEt3w7bCkedljhd2EwjLk+WkAJW/GGscZ8jNFeP0+gDhL8f6ohJpHTEoL0pDQBOx9m+iI0IqyDKFFbQOED6OmW3fzaMoewz4YcjY3DrW4UEIdxfbdhPeZpNjSuddpKxF+Enz40oYcNVH1IFgAmAoAq6YJQLFgQVcJ7C8HWc5FSOxIflK4H0eeqKq5xK7FZ9MSNl3D8ekb2DwBSjpGIvcE2OqMwq1jjqIpaIqeEh3es7XQ2+kskEw9fkka4OK+wAtVUJNY+W97jhKKUKXfd1SR2oryumcRJaHLFv/1HicTknKrg4n89Ic7fFFsjjEyX4ZKsVvtRyxXpvsUig7CS6Gx/yw+OfsfRgypX5EJ09j6GiHEem99n6Vvr9caDspTAm2T75phdgrOgLx3RSRQgowjAgNj4FgPTgkenlCf9jZmNIR1xth/Io62f777rIBUjMXHtGlfB76Og3FI=
#  email:
#    secure: AqGxLjyhtTDKYkRdLrhLD3ZoS8KLaE1AgkkX7Fr2QFvDaQpdHOKqcmbUAEQalTC1KWQ8lmtVD5mNiK2R/X9i0mpMERWuFxSYBSp5JP6F+nLdFrPrJIPOofahx+eyFhQoK5N2UEqwohKh/XIs9WlMi4HHSktXFncI8GgsuutVJD6Jr54tN0hwsbHHE76FkqbxrDZTAvU0+qW9yGnvCYc8hct/K1bLo5D02k7RT12yqrxuC37A3CL4lwI6PBxLDYVMQ6sgwZhyPwfpTy4wO1YbK6X4rKu2Vln7CyRRr0/D7Yn3cpU+vCO+6+PO2pU2Lziri+eK0wG/Ek5R/isl80uRjNPYBnZdfP1I6GpBEsJFHlP4JruB2tTVwP6+akh9X2z0sCa+lHeKP7nuE2H/NItkjtZSQkqIfn9zHCX1U+ZLqoG0u3mXNrVwtnMvrVzYO0ZIdkSosBYpU868xVM7549qaynhPh5sJtyHc1F5SQngbf4NARPLvjVqthUtpBF2w7nU0xPbGJf0rbpLdgj6N4pd7TguMLCxf6hMlmDQrVdr7rKAgZsHRjkb/A34z+U96qcocC5XDU4VJfNf5YUFVJjIyy5iIEuVKDhIcLaue6McqvFQ2y7R+FJCrUY0ZJmbqjKKCOGgDNBHxWil9uuTzBfZA2lbRPmYDquEcoeGpmSJoX0=
#  provider: npm
#  skip_cleanup: true
#  on:
#    tags: true
